# Generated by Django 5.2.6 on 2025-11-05 04:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("dishes", "0002_alter_technologicalmap_options_alter_dish_category_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={
                "ordering": ["-date"],
                "verbose_name": "Договор",
                "verbose_name_plural": "Договора",
            },
        ),
        migrations.AlterField(
            model_name="contract",
            name="counterparty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contracts.counterparty",
                verbose_name="Организация",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date",
            field=models.DateField(verbose_name="Дата договора"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contracts/contracts_files",
                verbose_name="Файл договора",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="is_actual",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Актуальность"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="products",
            field=models.ManyToManyField(
                through="contracts.ContractComposition",
                through_fields=("contract", "product"),
                to="dishes.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="staff.staff",
                verbose_name="Ответственный сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="contractcomposition",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="composition",
                to="contracts.contract",
                verbose_name="Договор",
            ),
        ),
        migrations.AlterField(
            model_name="contractcomposition",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Полная стоимость"
            ),
        ),
        migrations.AlterField(
            model_name="contractcomposition",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="dishes.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="contractcomposition",
            name="received_volume",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=15,
                verbose_name="Принято, кг",
            ),
        ),
        migrations.AlterField(
            model_name="contractcomposition",
            name="total_volume",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=15,
                verbose_name="Количество по договору, кг",
            ),
        ),
    ]
