# Generated by Django 5.2.6 on 2025-11-05 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technologicalmap",
            options={
                "get_latest_by": "date",
                "ordering": ["-date"],
                "verbose_name": "Технологическая карта",
                "verbose_name_plural": "Технологические карты",
            },
        ),
        migrations.AlterField(
            model_name="dish",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dishes",
                to="dishes.foodcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="technologicalmap",
            name="date",
            field=models.DateField(verbose_name="ТТК актуально с даты"),
        ),
        migrations.AlterField(
            model_name="technologicalmap",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technological_maps",
                to="dishes.dish",
            ),
        ),
        migrations.AlterField(
            model_name="technologicalmapcomposition",
            name="technological_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="composition",
                to="dishes.technologicalmap",
            ),
        ),
    ]
