# Generated by Django 5.2.6 on 2025-11-05 04:03

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationforstudentmeals",
            options={
                "ordering": ["-date"],
                "verbose_name": "Заявка на питание",
                "verbose_name_plural": "Заявки на питание",
            },
        ),
        migrations.AlterModelOptions(
            name="menurequirement",
            options={
                "ordering": ["-date"],
                "verbose_name": "Меню-требование",
                "verbose_name_plural": "Меню-требования",
            },
        ),
        migrations.AlterModelOptions(
            name="nutrientnormative",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Норматив нутриентов",
                "verbose_name_plural": "Нормативы нутриентов",
            },
        ),
        migrations.AlterField(
            model_name="cyclemenucomposition",
            name="cycle_menu_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="composition",
                to="main.cyclemenu",
            ),
        ),
        migrations.AlterField(
            model_name="menurequirement",
            name="date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 11, 5))
                ],
                verbose_name="Дата требования",
            ),
        ),
        migrations.AlterField(
            model_name="menurequirementcomposition",
            name="menu_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="composition",
                to="main.menurequirement",
            ),
        ),
    ]
