# Generated by Django 5.2.6 on 2025-11-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptance",
            options={
                "ordering": ["-datetime"],
                "verbose_name": "Приём на склад",
                "verbose_name_plural": "Приёмы на склады",
            },
        ),
        migrations.AlterModelOptions(
            name="factavailability",
            options={
                "ordering": ["-datetime"],
                "verbose_name": "Фактическое наличие на складе",
                "verbose_name_plural": "Фактическое наличие на складе",
            },
        ),
        migrations.AlterModelOptions(
            name="writeoff",
            options={
                "ordering": ["-datetime"],
                "verbose_name": "Списание co склада",
                "verbose_name_plural": "Списания co складов",
            },
        ),
    ]
